version: "3.8"

networks:
  ewb-net:
    driver: bridge

services:
  restapi:
    build: ./restapi
    container_name: ewb-restapi
    ports:
      - 82:82
    environment:
      SOLR_URL: http://solr:8983
    depends_on:
      - solr
    networks:
      - ewb-net 
    volumes:
      - ./data/source:/data/source
      - ./ewb_config:/config
   
  initializer:
    image: alpine
    container_name: ewb-solr-initializer
    restart: "no"
    entrypoint: |
      /bin/sh -c "chown 8983:8983 /solr"
    volumes:
      - ./db/data/solr:/solr

  solr:
    image: solr:9.1.1
    container_name: ewb-solr
    restart: always
    volumes:
      - ./db/data/solr:/var/solr
      - ./solr_config:/opt/solr/server/solr
    ports:
      - 8983:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044 -Djute.maxbuffer=0x5000000"
    networks:
      - ewb-net

  zoo:
    image: zookeeper
    container_name: ewb-zoo
    restart: always
    ports:
      - 2180:8080
      - 2181:2181
    environment:
      - JVMFLAGS=-Djute.maxbuffer=50000000
    volumes:
      - ./db/data/zoo/data:/data
      - ./db/data/zoo/logs:/datalog
    networks:
      - ewb-net

  solr-config:
    build: ./solr_config
    container_name: ewb-solr_config
    ports:
      - 81:81
    depends_on:
      - solr
      - zoo
    networks:
      - ewb-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./solr_config/bash_scripts:/bash_scripts
      - ./db/data/solr:/db/data/solr
    command: 
      - sh
      - -c
      - 'chmod +x /bash_scripts/init_config.sh && ls /bash_scripts && bash_scripts/init_config.sh /db/data/solr/data'
  
  dash-app:
    build: ./dash-app
    container_name: dash-app
    ports:
      - 8050:8050  
    networks:
      - ewb-net
    environment:
      RESTAPI_URL: http://ewb-restapi:82
    volumes:
      - ./dash-app:/dash-app  
      - ./data/source:/data/source